apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portfolio-tracker.fullname" . }}-secrets
  labels:
    {{- include "portfolio-tracker.labels" . | nindent 4 }}
type: Opaque
stringData:
  alpha-vantage-api-key: {{ .Values.config.alphaVantageApiKey | quote }}
